### ISSUE TITLE
Can't have a multi follow a multi

### ISSUE THREAD

**Issue by yochem** [padde/UncommEnter.vim#2]
It works fine, but I get a lot of errors when using it.

## Version nums
- neovim v0.2.2
- newest version uncommenter

## Steps to reproduce
1. Open a C-file in neovim (`nvim uncom.c`)
2. Insert `/*` and hit enter

<img width="1022" alt="image" src="https://user-images.githubusercontent.com/23235841/66109526-285cd000-e5c5-11e9-9132-fa9287661d7a.png">

After hitting enters to discard the errors, it still inserts a `*` on a new line. (So the behaviour is as expected).

Please let me know when I forgot to mention something.

**Comment by Anton-Wessel** [comment]
I have now the same problem and need help. on Kubuntu 22.04, vim 8.2, patches 1-3995. A long search pattern works when used in normal mode like /pattern/. But when same pattern used in Ex command line like :exec "normal /pattern/\<CR>" it gives the error E871. One problem I have solved: when in ex cmdline, in :exec "normal ...\<CR>", the backslashes bevore braces \{\} must be doubled \\{\\}. But I don't know how to prevent the error. --- regards anton
